spring.profiles.include: cache-members
app:
  cache:
    managementCenter:
      enabled: false
      update-interval: 3
      url: 
    tcpConfig:
      enabled: true
    query:
      pool-size: 10
      queue-capacity: 100
    cart:
      write-delay-seconds: 20
      write-batch-size: 200