# ************************************************************************
# This is the SB configuration of OAuth2 application for local mode.
# 
# Required Common configuration:
# - ERP - 
# - Database - 
# - Elasticsearch - 
# - Liquibase - 
# - Caching - 
# - Country Code - 
#
# ************************************************************************
spring.profiles.include: 
  wint-dev,
  db-sb, 
  elasticsearch-dev2,
  no-liquibase, 
  cache-dev, 
  country-sb

# https://devops.datenkollektiv.de/banner.txt/index.html Banner Font: doom
spring.banner.location: classpath:banner/banner_sb.txt
