spring.profiles: gtmotive-at-pre

external:
  webservice:
    ## production: info@normauto.ch
    normautoAddress: evangelos.vardakis@bbv.gr
# GTMotive connection
    gtmotive:
      url: https://estimate.mygtmotive.com/webservice/GtInterfaceWS.asmx
      multilang: true
      accounts:
        de:
          clientid: SAG_AT
          userid: ctlgpro
          password: FC3306DA3A
          gsId: SGS029700N
        fr:
          clientid: SAG_AT
          userid: ctlgpro
          password: FC3306DA3A
          gsId: SGS029700N
        it:
          clientid: SAG_AT
          userid: ctlgpro
          password: FC3306DA3A
          gsId: SGS029700N
    vehicle:
      url: https://wsgti.gtestimate.com/WSGtVehicleInformationService.svc
      gsId: SGS029700N
      password: FC3306DA3A
      customerId: SAG_AT
      userId: wsuserdev
    gtmotive-main-module:
      url: https://wsgti.gtestimate.com/WSGtService.svc
      accounts:
        de:
          clientid: SAG_AT
          userid: wsuserdev
          password: FC3306DA3A
          gsId: SGS029700N
        fr:
          clientid: SAG_AT
          userid: wsuserdev
          password: FC3306DA3A
          gsId: SGS029700N
        it:
          clientid: SAG_AT
          userid: wsuserdev
          password: FC3306DA3A
          gsId: SGS029700N
