# ************************************************************************
# This is the CH configuration of DVSE(SOAP) application for Feature mode.
# 
# Required Common configuration:
# - Elasticsearch -
# - ERP -
# - MDM for DVSE service - 
# - Database - 
# - Thread Executor Pool - 
# - Liquibase - 
# - Logging - 
# - Caching - 
# - Incentive - 
# - SOAP - 
# - Country Code - 
# -  Proxy - 
# - Java Melody Monitoring - 
#
# ************************************************************************
spring.profiles.include:
  elasticsearch-dev,
  mail-dev,
  ax-pre-cloud,
  mdm-prod,
  db-dev,
  executor-pool,
  no-liquibase,
  logging-ch-feature,
  actuator,
  cache-dev,
  incentive-dev,
  soap,
  country-ch,
  no-proxy,
  javamelody

spring.banner.location: classpath:banner/banner_ch.txt
